### ISSUE TITLE
FPGA Bitfiles installed in ZIP files

### ISSUE THREAD

**Issue by leesecho** [NISystemsEngineering/LinuxSharedMemoryAndDCAFExample#6]
FPGABitiles ZIP file (newest lv version, "superset") needs to be extracted to: <labview>\vi.lib\NI\SMI\FPGABitfiles\ directory, then installer LV version FPGABitfiles ("subset") ZIP file needs to be extracted and contents replace files of the same name in destination directory.

These steps would be accomplished with installer helper VIs as part of the package installation, the first step probably being the install of the ZIP files on the local machine.

**Comment by ryanpoulos** [comment]
@leesecho is this for a different repo?

**Comment by leesecho** [comment]
Yes, somehow put it in the wrong place.
